apiVersion: v1
kind: Service
metadata:
  name: assets
  namespace: assets
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: service
    app.kubernetes.io/instance: assets
    app.kubernetes.io/name: assets
  type: ClusterIP