---
apiVersion: v1
kind: Service
metadata:
  name: checkout
  namespace: checkout
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: service
    app.kubernetes.io/instance: checkout
    app.kubernetes.io/name: checkout
  type: ClusterIP