---
apiVersion: v1
kind: Service
metadata:
  name: carts-dynamodb
  namespace: carts
spec:
  ports:
  - name: dynamodb
    port: 8000
    protocol: TCP
    targetPort: dynamodb
  selector:
    app.kubernetes.io/component: dynamodb
    app.kubernetes.io/instance: carts
    app.kubernetes.io/name: carts
  type: ClusterIP