apiVersion: v1
data:
  name: b3JkZXJz
  password: ZGVmYXVsdF9wYXNzd29yZA==
  url: amRiYzptYXJpYWRiOi8vb3JkZXJzLW15c3FsOjMzMDYvb3JkZXJz
  username: b3JkZXJzX3VzZXI=
kind: Secret
metadata:
  name: orders-db
  namespace: orders
---

