---
apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: orders
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: service
    app.kubernetes.io/instance: orders
    app.kubernetes.io/name: orders
  type: ClusterIP