

---
apiVersion: v1
kind: Service
metadata:
  name: orders-mysql
  namespace: orders
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: mysql
  selector:
    app.kubernetes.io/component: mysql
    app.kubernetes.io/instance: orders
    app.kubernetes.io/name: orders
  type: ClusterIP